### ISSUE TITLE
django.db.utils.OperationalError: no such table: api_tsuser

### ISSUE THREAD

**Issue by sathapae** [pchaivong/wippie#8]

**Comment by sathapae** [comment]
I am trying to create superuser, but end up with the error no such table: api_tsuser. Is there any chnage? or Did I do anything wrong?

(env) D:\Python_Tutorial\workspace\wippie\wippie>python manage.py createsuperuser
Email address: sathapae@gmail.com
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\core\management__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\core\management__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\core\management\base.py", line 393, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 50, in execute
    return super(Command, self).execute(_args, *_options)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\core\management\base.py", line 444, in execute
    output = self.handle(_args, *_options)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 105, in handle
    self.UserModel._default_manager.db_manager(database).get_by_natural_key(username)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\contrib\auth\models.py", line 162, in get_by_natural_key
    return self.get(*_{self.model.USERNAME_FIELD: username})
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(_args, **kwargs)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\models\query.py", line 328, in get
    num = len(clone)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\models\query.py", line 144, in __len__
    self._fetch_all()
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\models\query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\models\query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\models\sql\compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\Python_Tutorial\workspace\wippie\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: api_tsuser

(env) D:\Python_Tutorial\workspace\wippie\wippie>

**Comment by sathapae** [comment]
@pchaivong 
Please ignore this one. I try to do again and it works fine.

**Comment by pchaivong** [comment]
If you find this kind of error again, try to rebuild new database

python manage.py makemigrations

and then 

python manage.py migrate

These two commands will recreate the database

Actually, It's must, when we change something in our model. We have to make those changes reflect on our database as well by those two commands

Happy Coding
Cheers.
